---
title: System Sequence Diagram - Start New Game & Set Policy
---
sequenceDiagram
    actor Player
    participant System as :System
    autonumber

    Player->>System: startNewGame
    System-->>Player: RequestCityDetails
    Note right of Player: Player inputs name and selects Strategy
    Player->>System: configureGame(CityName, Policy)
    System-->>Player: displayCityDashboard